/* Phrases d'exemple pour les mots isolés.

   Un mot seul ne se drille que d'une poignée de façons : reconnaître, traduire,
   taper, dire. Avec une phrase, il devient aussi un texte à trous, des tuiles à
   remettre en ordre, une dictée — et surtout il se rencontre là où on l'emploie,
   avec son article, sa place dans la phrase, ses voisins habituels.

   Deux phrases par mot, tirées au sort : le même mot ne revient donc pas dans la
   même phrase deux fois de suite.

   Règles d'écriture :
   - la phrase contient le mot, tel quel, sinon le texte à trous n'a rien à cacher ;
   - du flamand courant, pas du néerlandais de manuel : « ge » et « gij » à leur
     place, « hesp » plutôt que « ham », « pintje » plutôt que « bier » ;
   - court (quatre à huit mots), du vocabulaire déjà rencontré ;
   - {stad} et {bedrijf} sont remplacés par les réponses de la personne. */
(function () {
  'use strict';
  const S = (nl, fr, gap) => ({ nl, fr, gap });

  const EX = {
    /* ---- unité 1 : survivre ---- */
    'verstaan': [S('Sorry, ik kan u niet verstaan.', 'Pardon, je ne vous comprends pas.', 'verstaan'),
      S('Hebt ge dat verstaan?', 'Tu as compris ?', 'verstaan')],
    'herhalen': [S('Kunt ge dat nog eens herhalen?', 'Pouvez-vous répéter encore une fois ?', 'herhalen'),
      S('Ik ga het langzaam herhalen.', 'Je vais le répéter lentement.', 'herhalen')],
    'betekenen': [S('Wat betekent dat woord?', 'Que signifie ce mot ?', 'betekent'),
      S('Dat kan twee dingen betekenen.', 'Ça peut signifier deux choses.', 'betekenen')],
    'proberen': [S('Ik probeer het in het Nederlands.', 'J’essaie en néerlandais.', 'probeer'),
      S('Probeer het nog eens, trager.', 'Essaie encore une fois, plus lentement.', 'Probeer')],
    'spreken': [S('Spreekt ge een beetje Frans?', 'Vous parlez un peu français ?', 'Spreekt'),
      S('Ik spreek nog niet goed Nederlands.', 'Je ne parle pas encore bien néerlandais.', 'spreek')],
    'leren': [S('Ik leer Nederlands voor mijn werk.', 'J’apprends le néerlandais pour mon travail.', 'leer'),
      S('Mijn kinderen leren snel.', 'Mes enfants apprennent vite.', 'leren')],
    'zeggen': [S('Hoe zegt ge dat in het Nederlands?', 'Comment dit-on ça en néerlandais ?', 'zegt'),
      S('Zeg het maar in het Frans.', 'Dis-le donc en français.', 'Zeg')],
    'helpen': [S('Kan ik u helpen?', 'Puis-je vous aider ?', 'helpen'),
      S('Mijn collega helpt mij altijd.', 'Mon collègue m’aide toujours.', 'helpt')],
    'graag': [S('Ik werk graag met u samen.', 'J’aime bien travailler avec vous.', 'graag'),
      S('Een koffie, graag.', 'Un café, s’il vous plaît.', 'graag')],
    'trager': [S('Kunt ge wat trager spreken?', 'Pouvez-vous parler un peu plus lentement ?', 'trager'),
      S('Trager, alstublieft.', 'Plus lentement, s’il vous plaît.', 'Trager')],

    /* ---- unité 2 : moi et toi ---- */
    'heten': [S('Ik heet Tom en ik woon hier.', 'Je m’appelle Tom et j’habite ici.', 'heet'),
      S('Hoe heet uw collega?', 'Comment s’appelle votre collègue ?', 'heet')],
    'wonen': [S('Wij wonen al vijf jaar in {stad}.', 'Nous habitons à {stad} depuis cinq ans.', 'wonen'),
      S('Mijn zus woont in Gent.', 'Ma sœur habite à Gand.', 'woont')],
    'komen': [S('Ik kom uit Frankrijk.', 'Je viens de France.', 'kom'),
      S('Komt ge morgen naar kantoor?', 'Tu viens au bureau demain ?', 'Komt')],
    'werken': [S('Ik werk bij {bedrijf}.', 'Je travaille chez {bedrijf}.', 'werk'),
      S('Zij werkt van thuis uit.', 'Elle travaille de chez elle.', 'werkt')],
    'de naam': [S('Wat is uw naam, alstublieft?', 'Quel est votre nom, s’il vous plaît ?', 'naam'),
      S('Ik ben uw naam vergeten.', 'J’ai oublié votre nom.', 'naam')],
    'het jaar': [S('Ik woon hier al vijf jaar.', 'J’habite ici depuis cinq ans.', 'jaar'),
      S('Volgend jaar spreek ik beter Nederlands.', 'L’an prochain je parlerai mieux néerlandais.', 'jaar')],
    'getrouwd': [S('Ik ben getrouwd en heb twee kinderen.', 'Je suis marié et j’ai deux enfants.', 'getrouwd'),
      S('Zijn zus is niet getrouwd.', 'Sa sœur n’est pas mariée.', 'getrouwd')],
    'samen': [S('Wij doen dat samen.', 'On fait ça ensemble.', 'samen'),
      S('Samen met mijn collega.', 'Avec mon collègue.', 'Samen')],
    'het Nederlands': [S('Mijn Nederlands is nog niet goed.', 'Mon néerlandais n’est pas encore bon.', 'Nederlands'),
      S('Spreken wij Nederlands of Frans?', 'On parle néerlandais ou français ?', 'Nederlands')],

    /* ---- unité 3 : nombres et heure ---- */
    'het uur': [S('De vergadering duurt een uur.', 'La réunion dure une heure.', 'uur'),
      S('Om hoe laat, om acht uur?', 'À quelle heure, à huit heures ?', 'uur')],
    'de minuut': [S('Ik ben er over vijf minuten.', 'J’y suis dans cinq minutes.', 'minuten'),
      S('Nog één minuut, alstublieft.', 'Encore une minute, s’il vous plaît.', 'minuut')],
    'de dag': [S('Elke dag neem ik de trein.', 'Chaque jour je prends le train.', 'dag'),
      S('Het is een lange dag geweest.', 'Ça a été une longue journée.', 'dag')],
    'de week': [S('Volgende week ben ik thuis.', 'La semaine prochaine je suis à la maison.', 'week'),
      S('Ik werk vier dagen per week.', 'Je travaille quatre jours par semaine.', 'week')],
    'de maand': [S('Volgende maand ga ik op vakantie.', 'Le mois prochain je pars en vacances.', 'maand'),
      S('Elke maand betaal ik de huur.', 'Chaque mois je paie le loyer.', 'maand')],
    'vandaag': [S('Vandaag werk ik van thuis.', 'Aujourd’hui je travaille de chez moi.', 'Vandaag'),
      S('Is de bakker vandaag open?', 'Le boulanger est ouvert aujourd’hui ?', 'vandaag')],
    'morgen': [S('Morgen ga ik naar de dokter.', 'Demain je vais chez le médecin.', 'Morgen'),
      S('Tot morgen, collega!', 'À demain, collègue !', 'morgen')],
    'gisteren': [S('Gisteren heb ik mijn buurman gezien.', 'Hier j’ai vu mon voisin.', 'Gisteren'),
      S('Dat was gisteren al klaar.', 'C’était déjà prêt hier.', 'gisteren')],
    'vroeg': [S('Ik sta elke dag vroeg op.', 'Je me lève tôt tous les jours.', 'vroeg'),
      S('Het is nog te vroeg.', 'Il est encore trop tôt.', 'vroeg')],
    'laat': [S('Sorry, ik ben te laat.', 'Désolé, je suis en retard.', 'laat'),
      S('Het wordt laat vanavond.', 'Ça va finir tard ce soir.', 'laat')],
    'straks': [S('Ik bel u straks terug.', 'Je vous rappelle tout à l’heure.', 'straks'),
      S('Tot straks!', 'À tout à l’heure !', 'straks')],

    /* ---- unité 4 : chez le boulanger ---- */
    'het brood': [S('Een half wit brood, alstublieft.', 'Un demi pain blanc, s’il vous plaît.', 'brood'),
      S('Het brood is nog warm.', 'Le pain est encore chaud.', 'brood')],
    'de pistolet': [S('Vier pistolets, graag.', 'Quatre pistolets, s’il vous plaît.', 'pistolets'),
      S('Een pistolet met hesp.', 'Un pistolet au jambon.', 'pistolet')],
    'de koffiekoek': [S('Twee koffiekoeken voor de kinderen.', 'Deux couques pour les enfants.', 'koffiekoeken'),
      S('Op zondag eten wij een koffiekoek.', 'Le dimanche on mange une couque.', 'koffiekoek')],
    'de bakker': [S('Ik ga snel naar de bakker.', 'Je vais vite chez le boulanger.', 'bakker'),
      S('De bakker is op maandag gesloten.', 'Le boulanger est fermé le lundi.', 'bakker')],
    'de beenhouwer': [S('De beenhouwer in onze straat is goed.', 'Le boucher de notre rue est bon.', 'beenhouwer'),
      S('Ik koop mijn hesp bij de beenhouwer.', 'J’achète mon jambon chez le boucher.', 'beenhouwer')],
    'de hesp': [S('Een broodje met hesp en kaas.', 'Un sandwich jambon fromage.', 'hesp'),
      S('Is die hesp van vandaag?', 'Ce jambon est d’aujourd’hui ?', 'hesp')],
    'de kaas': [S('Voor mij een broodje kaas.', 'Pour moi un sandwich au fromage.', 'kaas'),
      S('De kaas is nogal duur.', 'Le fromage est assez cher.', 'kaas')],
    'de boter': [S('Een beetje boter op mijn brood.', 'Un peu de beurre sur mon pain.', 'boter'),
      S('De boter staat in de keuken.', 'Le beurre est dans la cuisine.', 'boter')],
    'het broodje': [S('Ik neem een broodje mee naar het werk.', 'J’emporte un sandwich au travail.', 'broodje'),
      S('Dat broodje was echt lekker.', 'Ce sandwich était vraiment bon.', 'broodje')],
    'de koffie': [S('Een koffie zonder suiker, graag.', 'Un café sans sucre, s’il vous plaît.', 'koffie'),
      S('Drinkt ge koffie of thee?', 'Tu bois du café ou du thé ?', 'koffie')],
    'het water': [S('Een glas water, alstublieft.', 'Un verre d’eau, s’il vous plaît.', 'water'),
      S('Ik drink veel water op het werk.', 'Je bois beaucoup d’eau au travail.', 'water')],
    'de pint': [S('Een pintje na het werk.', 'Une bière après le travail.', 'pintje'),
      S('Zij drinkt geen pint.', 'Elle ne boit pas de bière.', 'pint')],
    'de frieten': [S('Op vrijdag eten wij frieten.', 'Le vendredi on mange des frites.', 'frieten'),
      S('De frieten hier zijn de beste.', 'Les frites ici sont les meilleures.', 'frieten')],
    'lekker': [S('Dat was heel lekker, dank u.', 'C’était très bon, merci.', 'lekker'),
      S('De taart van de bakker is lekker.', 'La tarte du boulanger est bonne.', 'lekker')],
    'kosten': [S('Hoeveel kost dat?', 'Combien ça coûte ?', 'kost'),
      S('Die taart kost tien euro.', 'Cette tarte coûte dix euros.', 'kost')],
    'meenemen': [S('Is dat om mee te nemen?', 'C’est à emporter ?', 'nemen'),
      S('Ik neem twee broodjes mee.', 'J’emporte deux sandwichs.', 'neem')],

    /* ---- unité 5 : chez toi ---- */
    'het huis': [S('Ons huis staat in een rustige straat.', 'Notre maison est dans une rue calme.', 'huis'),
      S('Het huis van de buren is groot.', 'La maison des voisins est grande.', 'huis')],
    'de straat': [S('Wij wonen in dezelfde straat.', 'Nous habitons dans la même rue.', 'straat'),
      S('In onze straat is het rustig.', 'Dans notre rue c’est calme.', 'straat')],
    'de tuin': [S('De kinderen spelen in de tuin.', 'Les enfants jouent dans le jardin.', 'tuin'),
      S('Onze tuin is niet groot.', 'Notre jardin n’est pas grand.', 'tuin')],
    'de buurman': [S('Mijn buurman spreekt alleen Nederlands.', 'Mon voisin ne parle que néerlandais.', 'buurman'),
      S('De buurman helpt mij met de tuin.', 'Le voisin m’aide avec le jardin.', 'buurman')],
    'de buren': [S('De buren zijn heel vriendelijk.', 'Les voisins sont très gentils.', 'buren'),
      S('Ik ken de buren nog niet.', 'Je ne connais pas encore les voisins.', 'buren')],
    'de keuken': [S('De sleutel ligt in de keuken.', 'La clé est dans la cuisine.', 'keuken'),
      S('Wij eten in de keuken.', 'On mange dans la cuisine.', 'keuken')],
    'de living': [S('De living is klein maar rustig.', 'Le salon est petit mais calme.', 'living'),
      S('In de living staat de televisie.', 'La télévision est dans le salon.', 'living')],
    'het gemeentehuis': [S('Morgen moet ik naar het gemeentehuis.', 'Demain je dois aller à la maison communale.', 'gemeentehuis'),
      S('Het gemeentehuis is om vier uur gesloten.', 'La maison communale ferme à seize heures.', 'gemeentehuis')],
    'de gemeente': [S('De gemeente stuurt alles in het Nederlands.', 'La commune envoie tout en néerlandais.', 'gemeente'),
      S('Onze gemeente is niet groot.', 'Notre commune n’est pas grande.', 'gemeente')],
    'het containerpark': [S('Zaterdag ga ik naar het containerpark.', 'Samedi je vais au parc à conteneurs.', 'containerpark'),
      S('Het containerpark is zondag gesloten.', 'Le parc à conteneurs est fermé le dimanche.', 'containerpark')],
    'het pakje': [S('Er ligt een pakje bij de buren.', 'Il y a un colis chez les voisins.', 'pakje'),
      S('Mijn pakje komt vandaag.', 'Mon colis arrive aujourd’hui.', 'pakje')],
    'de sleutel': [S('Ik ben mijn sleutel vergeten.', 'J’ai oublié ma clé.', 'sleutel'),
      S('De sleutel van de garage hangt daar.', 'La clé du garage est accrochée là.', 'sleutel')],
    'de deur': [S('Doe de deur maar dicht.', 'Ferme la porte.', 'deur'),
      S('Er staat iemand aan de deur.', 'Il y a quelqu’un à la porte.', 'deur')],
    'de brievenbus': [S('Niets in de brievenbus vandaag.', 'Rien dans la boîte aux lettres aujourd’hui.', 'brievenbus'),
      S('De brievenbus staat naast de deur.', 'La boîte aux lettres est à côté de la porte.', 'brievenbus')],
    'vriendelijk': [S('De buurvrouw is altijd vriendelijk.', 'La voisine est toujours gentille.', 'vriendelijk'),
      S('Dat is vriendelijk van u.', 'C’est gentil de votre part.', 'vriendelijk')],
    'rustig': [S('Het is hier rustig ’s avonds.', 'C’est calme ici le soir.', 'rustig'),
      S('Een rustige straat, zonder veel auto’s.', 'Une rue calme, sans beaucoup de voitures.', 'rustige')],

    /* ---- unité 6 : famille et gens ---- */
    'de vrouw': [S('Mijn vrouw werkt in Brussel.', 'Ma femme travaille à Bruxelles.', 'vrouw'),
      S('Die vrouw woont naast ons.', 'Cette femme habite à côté de chez nous.', 'vrouw')],
    'de zoon': [S('Mijn zoon gaat naar school in {stad}.', 'Mon fils va à l’école à {stad}.', 'zoon'),
      S('Hun zoon is al twintig.', 'Leur fils a déjà vingt ans.', 'zoon')],
    'de dochter': [S('Onze dochter leert snel Nederlands.', 'Notre fille apprend vite le néerlandais.', 'dochter'),
      S('De dochter van de buren is jong.', 'La fille des voisins est jeune.', 'dochter')],
    'het kind': [S('Het kind speelt buiten.', 'L’enfant joue dehors.', 'kind'),
      S('Dat kind spreekt twee talen.', 'Cet enfant parle deux langues.', 'kind')],
    'de kinderen': [S('De kinderen eten om zes uur.', 'Les enfants mangent à dix-huit heures.', 'kinderen'),
      S('Wij hebben twee kinderen.', 'Nous avons deux enfants.', 'kinderen')],
    'de ouders': [S('Mijn ouders wonen niet in België.', 'Mes parents n’habitent pas en Belgique.', 'ouders'),
      S('De ouders wachten aan de school.', 'Les parents attendent devant l’école.', 'ouders')],
    'de zus': [S('Mijn zus komt dit weekend.', 'Ma sœur vient ce week-end.', 'zus'),
      S('Zijn zus werkt bij de gemeente.', 'Sa sœur travaille à la commune.', 'zus')],
    'de broer': [S('Mijn broer spreekt geen Nederlands.', 'Mon frère ne parle pas néerlandais.', 'broer'),
      S('Haar broer woont in Gent.', 'Son frère habite à Gand.', 'broer')],
    'de vriend': [S('Een vriend van mij werkt daar.', 'Un ami à moi travaille là.', 'vriend'),
      S('Mijn vriend helpt mij met Nederlands.', 'Mon ami m’aide avec le néerlandais.', 'vriend')],
    'de collega': [S('Mijn collega spreekt alleen Nederlands.', 'Mon collègue ne parle que néerlandais.', 'collega'),
      S('Een collega van {bedrijf} komt ook.', 'Un collègue de {bedrijf} vient aussi.', 'collega')],
    'de baas': [S('De baas is er vandaag niet.', 'Le patron n’est pas là aujourd’hui.', 'baas'),
      S('Onze baas spreekt ook Frans.', 'Notre patron parle aussi français.', 'baas')],
    'de mensen': [S('De mensen hier zijn vriendelijk.', 'Les gens ici sont gentils.', 'mensen'),
      S('Veel mensen spreken twee talen.', 'Beaucoup de gens parlent deux langues.', 'mensen')],
    'de school': [S('De school begint om half negen.', 'L’école commence à huit heures et demie.', 'school'),
      S('Onze kinderen gaan hier naar school.', 'Nos enfants vont à l’école ici.', 'school')],
    'iedereen': [S('Iedereen spreekt Nederlands op het werk.', 'Tout le monde parle néerlandais au travail.', 'Iedereen'),
      S('Dat weet iedereen hier.', 'Tout le monde ici sait ça.', 'iedereen')],
    'niemand': [S('Er is niemand thuis.', 'Il n’y a personne à la maison.', 'niemand'),
      S('Niemand heeft dat gezegd.', 'Personne n’a dit ça.', 'Niemand')],
    'streng': [S('De baas is streng maar eerlijk.', 'Le patron est sévère mais juste.', 'streng'),
      S('Die school is streng.', 'Cette école est sévère.', 'streng')],

    /* ---- unité 7 : en route ---- */
    'de fiets': [S('Ik ga met de fiets naar het station.', 'Je vais à la gare à vélo.', 'fiets'),
      S('Mijn fiets staat buiten.', 'Mon vélo est dehors.', 'fiets')],
    'de auto': [S('De auto staat in de garage.', 'La voiture est au garage.', 'auto'),
      S('Met de auto duurt het langer.', 'En voiture ça prend plus longtemps.', 'auto')],
    'de trein': [S('De trein van acht uur heeft vertraging.', 'Le train de huit heures a du retard.', 'trein'),
      S('Ik neem elke dag de trein.', 'Je prends le train tous les jours.', 'trein')],
    'de bus': [S('De bus stopt aan de kerk.', 'Le bus s’arrête à l’église.', 'bus'),
      S('Wij wachten op de bus.', 'Nous attendons le bus.', 'bus')],
    'de tram': [S('De tram rijdt om de tien minuten.', 'Le tram passe toutes les dix minutes.', 'tram'),
      S('Neem de tram naar het centrum.', 'Prends le tram jusqu’au centre.', 'tram')],
    'het station': [S('Het station is dichtbij.', 'La gare est tout près.', 'station'),
      S('Ik zie u aan het station.', 'Je vous vois à la gare.', 'station')],
    'het perron': [S('De trein vertrekt van perron drie.', 'Le train part du quai trois.', 'perron'),
      S('Wij wachten op het perron.', 'Nous attendons sur le quai.', 'perron')],
    'de halte': [S('De halte is aan de overkant.', 'L’arrêt est en face.', 'halte'),
      S('Aan welke halte moet ik eruit?', 'À quel arrêt dois-je descendre ?', 'halte')],
    'de vertraging': [S('De trein heeft twintig minuten vertraging.', 'Le train a vingt minutes de retard.', 'vertraging'),
      S('Door de vertraging kom ik te laat.', 'À cause du retard j’arrive en retard.', 'vertraging')],
    'de file': [S('Er staat file richting Brussel.', 'Il y a des embouteillages vers Bruxelles.', 'file'),
      S('Met de trein sta ik niet in de file.', 'En train je ne suis pas dans les bouchons.', 'file')],
    'het kaartje': [S('Ik koop een kaartje aan de automaat.', 'J’achète un ticket au distributeur.', 'kaartje'),
      S('Uw kaartje, alstublieft.', 'Votre ticket, s’il vous plaît.', 'kaartje')],
    'vertrekken': [S('De trein vertrekt om half negen.', 'Le train part à huit heures et demie.', 'vertrekt'),
      S('Wij vertrekken morgen vroeg.', 'Nous partons demain tôt.', 'vertrekken')],
    'aankomen': [S('Ik kom om zes uur aan.', 'J’arrive à dix-huit heures.', 'kom'),
      S('Wanneer komt de trein aan?', 'Quand le train arrive-t-il ?', 'komt')],
    'overstappen': [S('In Gent moet ge overstappen.', 'À Gand tu dois changer.', 'overstappen'),
      S('Ik stap over in Brussel.', 'Je change à Bruxelles.', 'stap')],
    'links': [S('Aan de kerk gaat ge links.', 'À l’église tu tournes à gauche.', 'links'),
      S('Het station ligt links van de brug.', 'La gare est à gauche du pont.', 'links')],
    'rechts': [S('Neem de eerste straat rechts.', 'Prends la première rue à droite.', 'rechts'),
      S('De bakker staat rechts.', 'Le boulanger est à droite.', 'rechts')],
    'rechtdoor': [S('Ga rechtdoor tot aan de kerk.', 'Va tout droit jusqu’à l’église.', 'rechtdoor'),
      S('Rechtdoor en dan links.', 'Tout droit puis à gauche.', 'Rechtdoor')],
    'ver': [S('Is het nog ver naar het station?', 'C’est encore loin, la gare ?', 'ver'),
      S('Dat is niet ver van hier.', 'Ce n’est pas loin d’ici.', 'ver')],
    'dichtbij': [S('De halte is heel dichtbij.', 'L’arrêt est tout près.', 'dichtbij'),
      S('Woont ge dichtbij het werk?', 'Tu habites près du travail ?', 'dichtbij')],
    'duren': [S('De rit duurt een half uur.', 'Le trajet dure une demi-heure.', 'duurt'),
      S('Hoelang duurt de vergadering?', 'Combien de temps dure la réunion ?', 'duurt')],

    /* ---- unité 8 : le travail ---- */
    'het werk': [S('Ik ben om negen uur op het werk.', 'Je suis au travail à neuf heures.', 'werk'),
      S('Op het werk spreken wij Nederlands.', 'Au travail nous parlons néerlandais.', 'werk')],
    'de klant': [S('De klant wacht op een antwoord.', 'Le client attend une réponse.', 'klant'),
      S('Onze klant zit in Antwerpen.', 'Notre client est à Anvers.', 'klant')],
    'de vergadering': [S('De vergadering begint om tien uur.', 'La réunion commence à dix heures.', 'vergadering'),
      S('Ik zit in een vergadering.', 'Je suis en réunion.', 'vergadering')],
    'het project': [S('Het project is bijna klaar.', 'Le projet est presque terminé.', 'project'),
      S('Ik werk aan twee projecten.', 'Je travaille sur deux projets.', 'projecten')],
    'de code': [S('Ik schrijf de code vandaag.', 'J’écris le code aujourd’hui.', 'code'),
      S('De code draait al op de server.', 'Le code tourne déjà sur le serveur.', 'code')],
    'de test': [S('De test is groen.', 'Le test passe.', 'test'),
      S('Ik schrijf eerst een test.', 'J’écris d’abord un test.', 'test')],
    'de fout': [S('Er zit een fout in de code.', 'Il y a une erreur dans le code.', 'fout'),
      S('Die fout is nu opgelost.', 'Cette erreur est résolue maintenant.', 'fout')],
    'het probleem': [S('Het probleem zit in de databank.', 'Le problème est dans la base de données.', 'probleem'),
      S('Geen probleem, ik doe dat.', 'Pas de problème, je m’en occupe.', 'probleem')],
    'de oplossing': [S('Ik heb een oplossing gevonden.', 'J’ai trouvé une solution.', 'oplossing'),
      S('De oplossing is eenvoudig.', 'La solution est simple.', 'oplossing')],
    'het ticket': [S('Ik maak een ticket aan voor dat probleem.', 'Je crée un ticket pour ce problème.', 'ticket'),
      S('Dat ticket is nog niet klaar.', 'Ce ticket n’est pas encore terminé.', 'ticket')],
    'de deadline': [S('De deadline is vrijdag.', 'La deadline est vendredi.', 'deadline'),
      S('Wij halen de deadline niet.', 'Nous n’allons pas tenir la deadline.', 'deadline')],
    'de planning': [S('Dat staat niet in de planning.', 'Ce n’est pas dans le planning.', 'planning'),
      S('De planning verandert elke week.', 'Le planning change chaque semaine.', 'planning')],
    'de databank': [S('De databank is traag vandaag.', 'La base de données est lente aujourd’hui.', 'databank'),
      S('Die gegevens staan in de databank.', 'Ces données sont dans la base.', 'databank')],
    'de server': [S('De server is even niet bereikbaar.', 'Le serveur est momentanément injoignable.', 'server'),
      S('De code staat op de server.', 'Le code est sur le serveur.', 'server')],
    'de mail': [S('Ik stuur u een mail.', 'Je vous envoie un mail.', 'mail'),
      S('Uw mail is goed aangekomen.', 'Votre mail est bien arrivé.', 'mail')],
    'het verslag': [S('Ik schrijf het verslag van de vergadering.', 'J’écris le compte rendu de la réunion.', 'verslag'),
      S('Het verslag staat in de mail.', 'Le compte rendu est dans le mail.', 'verslag')],
    'het thuiswerk': [S('Op dinsdag doe ik thuiswerk.', 'Le mardi je télétravaille.', 'thuiswerk'),
      S('Thuiswerk is hier normaal.', 'Le télétravail est normal ici.', 'Thuiswerk')],
    'het kantoor': [S('Ik ben morgen op kantoor.', 'Je suis au bureau demain.', 'kantoor'),
      S('Het kantoor sluit om zes uur.', 'Le bureau ferme à dix-huit heures.', 'kantoor')],
    'de afspraak': [S('Ik heb een afspraak om drie uur.', 'J’ai un rendez-vous à quinze heures.', 'afspraak'),
      S('Kunnen wij een afspraak maken?', 'Pouvons-nous prendre rendez-vous ?', 'afspraak')],
    'klaar': [S('Het verslag is klaar.', 'Le compte rendu est prêt.', 'klaar'),
      S('Ik ben klaar met dat ticket.', 'J’ai fini ce ticket.', 'klaar')],
    'bezig': [S('Ik ben bezig met de test.', 'Je suis en train de faire le test.', 'bezig'),
      S('Zij is nog bezig.', 'Elle est encore occupée.', 'bezig')],
    'dringend': [S('Dat is dringend, sorry.', 'C’est urgent, désolé.', 'dringend'),
      S('Een dringende vraag van de klant.', 'Une question urgente du client.', 'dringende')],
    'sturen': [S('Ik stuur het verslag morgen.', 'J’envoie le compte rendu demain.', 'stuur'),
      S('Kunt ge mij dat sturen?', 'Peux-tu m’envoyer ça ?', 'sturen')],
    'uitleggen': [S('Kunt ge dat nog eens uitleggen?', 'Pouvez-vous réexpliquer ça ?', 'uitleggen'),
      S('Ik leg het probleem kort uit.', 'J’explique brièvement le problème.', 'leg')],
    'oplossen': [S('Ik ga dat vandaag oplossen.', 'Je vais résoudre ça aujourd’hui.', 'oplossen'),
      S('Het probleem is opgelost.', 'Le problème est résolu.', 'opgelost')],
    'draaien': [S('De test draait nu.', 'Le test tourne maintenant.', 'draait'),
      S('Dat draait niet op mijn omgeving.', 'Ça ne tourne pas sur mon environnement.', 'draait')],

    /* ---- unité 9 : la journée ---- */
    'opstaan': [S('Ik sta elke dag om zes uur op.', 'Je me lève à six heures tous les jours.', 'sta'),
      S('Op zondag staan wij laat op.', 'Le dimanche nous nous levons tard.', 'staan')],
    'ontbijten': [S('Wij ontbijten samen om zeven uur.', 'Nous déjeunons ensemble à sept heures.', 'ontbijten'),
      S('Ik ontbijt met een koffiekoek.', 'Je prends une couque au petit-déjeuner.', 'ontbijt')],
    'thuiskomen': [S('Ik kom rond zes uur thuis.', 'Je rentre vers dix-huit heures.', 'kom'),
      S('Zij komt later thuis.', 'Elle rentre plus tard.', 'komt')],
    'afspreken': [S('Zullen wij iets afspreken voor vrijdag?', 'On convient de quelque chose pour vendredi ?', 'afspreken'),
      S('Wij spreken af om acht uur.', 'On se donne rendez-vous à huit heures.', 'spreken')],
    'opbellen': [S('Ik bel de dokter straks op.', 'J’appelle le médecin tout à l’heure.', 'bel'),
      S('Kunt ge mij morgen opbellen?', 'Peux-tu m’appeler demain ?', 'opbellen')],
    'slapen': [S('De kinderen slapen al.', 'Les enfants dorment déjà.', 'slapen'),
      S('Ik heb slecht geslapen.', 'J’ai mal dormi.', 'geslapen')],
    'eten': [S('Wij eten om zeven uur.', 'Nous mangeons à dix-neuf heures.', 'eten'),
      S('Op vrijdag eten wij frieten.', 'Le vendredi on mange des frites.', 'eten')],
    'drinken': [S('Ik drink veel water.', 'Je bois beaucoup d’eau.', 'drink'),
      S('Drinkt ge iets na het werk?', 'Tu bois quelque chose après le travail ?', 'Drinkt')],
    'koken': [S('Vanavond kook ik.', 'Ce soir je cuisine.', 'kook'),
      S('Mijn vrouw kookt beter dan ik.', 'Ma femme cuisine mieux que moi.', 'kookt')],
    'wandelen': [S('Op zondag gaan wij wandelen.', 'Le dimanche nous allons nous promener.', 'wandelen'),
      S('Ik wandel elke avond een half uur.', 'Je marche une demi-heure chaque soir.', 'wandel')],
    'de avond': [S('’s Avonds ben ik moe.', 'Le soir je suis fatigué.', 'Avonds'),
      S('Een rustige avond thuis.', 'Une soirée calme à la maison.', 'avond')],
    'moe': [S('Ik ben moe na een lange dag.', 'Je suis fatigué après une longue journée.', 'moe'),
      S('De kinderen zijn moe.', 'Les enfants sont fatigués.', 'moe')],
    'druk': [S('Het was een drukke dag.', 'Ça a été une journée chargée.', 'drukke'),
      S('Volgende week is het druk op het werk.', 'La semaine prochaine c’est chargé au travail.', 'druk')],
    'altijd': [S('Ik neem altijd de trein van acht uur.', 'Je prends toujours le train de huit heures.', 'altijd'),
      S('Zij komt altijd te laat.', 'Elle arrive toujours en retard.', 'altijd')],
    'soms': [S('Soms ga ik met de fiets.', 'Parfois j’y vais à vélo.', 'Soms'),
      S('Ik werk soms van thuis.', 'Je travaille parfois de chez moi.', 'soms')],
    'nooit': [S('Ik drink nooit koffie ’s avonds.', 'Je ne bois jamais de café le soir.', 'nooit'),
      S('Dat gebeurt hier nooit.', 'Ça n’arrive jamais ici.', 'nooit')],
    'meestal': [S('Meestal eten wij om zeven uur.', 'La plupart du temps on mange à dix-neuf heures.', 'Meestal'),
      S('Ik neem meestal de trein.', 'Je prends généralement le train.', 'meestal')],
    'eerst': [S('Eerst koffie, daarna de mail.', 'D’abord le café, ensuite les mails.', 'Eerst'),
      S('Ik doe eerst het dringende werk.', 'Je fais d’abord le travail urgent.', 'eerst')],
    'daarna': [S('Daarna ga ik naar de winkel.', 'Ensuite je vais au magasin.', 'Daarna'),
      S('Eerst eten, daarna wandelen.', 'D’abord manger, ensuite se promener.', 'daarna')],

    /* ---- unité 10 : courses et argent ---- */
    'de winkel': [S('De winkel is om negen uur open.', 'Le magasin ouvre à neuf heures.', 'winkel'),
      S('Ik ga snel naar de winkel.', 'Je vais vite au magasin.', 'winkel')],
    'de kassa': [S('Betalen doet ge aan de kassa.', 'On paie à la caisse.', 'kassa'),
      S('Aan de kassa staat een lange rij.', 'Il y a une longue file à la caisse.', 'kassa')],
    'het geld': [S('Ik heb geen geld bij.', 'Je n’ai pas d’argent sur moi.', 'geld'),
      S('Dat kost veel geld.', 'Ça coûte beaucoup d’argent.', 'geld')],
    'de kaart': [S('Ik betaal met de kaart.', 'Je paie par carte.', 'kaart'),
      S('Uw kaart werkt niet.', 'Votre carte ne fonctionne pas.', 'kaart')],
    'de korting': [S('Er is korting op het brood.', 'Il y a une réduction sur le pain.', 'korting'),
      S('Met korting kost het zes euro.', 'Avec la réduction ça coûte six euros.', 'korting')],
    'de bon': [S('Wilt ge de bon?', 'Voulez-vous le ticket ?', 'bon'),
      S('Ik heb de bon nog.', 'J’ai encore le ticket.', 'bon')],
    'het zakje': [S('Een zakje, alstublieft.', 'Un sachet, s’il vous plaît.', 'zakje'),
      S('Het zakje kost tien cent.', 'Le sachet coûte dix centimes.', 'zakje')],
    'de maat': [S('Hebt ge dit in een andere maat?', 'Vous avez ceci dans une autre taille ?', 'maat'),
      S('Die maat is te klein.', 'Cette taille est trop petite.', 'maat')],
    'de kleur': [S('Die kleur staat u goed.', 'Cette couleur vous va bien.', 'kleur'),
      S('In welke kleuren hebt ge dat?', 'Vous avez ça dans quelles couleurs ?', 'kleuren')],
    'duur': [S('Dat is te duur voor mij.', 'C’est trop cher pour moi.', 'duur'),
      S('De kaas is duur geworden.', 'Le fromage est devenu cher.', 'duur')],
    'goedkoop': [S('Met de fiets is het goedkoop.', 'À vélo c’est bon marché.', 'goedkoop'),
      S('Dat is goedkoper in de winkel hiernaast.', 'C’est moins cher dans le magasin d’à côté.', 'goedkoper')],
    'gratis': [S('De levering is gratis.', 'La livraison est gratuite.', 'gratis'),
      S('Voor kinderen is het gratis.', 'Pour les enfants c’est gratuit.', 'gratis')],
    'kopen': [S('Ik koop brood bij de bakker.', 'J’achète du pain chez le boulanger.', 'koop'),
      S('Wij kopen dat online.', 'Nous achetons ça en ligne.', 'kopen')],
    'betalen': [S('Kan ik met de kaart betalen?', 'Puis-je payer par carte ?', 'betalen'),
      S('Ik betaal elke maand de huur.', 'Je paie le loyer chaque mois.', 'betaal')],
    'ruilen': [S('Kan ik dit ruilen?', 'Puis-je échanger ceci ?', 'ruilen'),
      S('Met de bon kunt ge ruilen.', 'Avec le ticket vous pouvez échanger.', 'ruilen')],
    'zoeken': [S('Ik zoek een cadeau voor mijn vrouw.', 'Je cherche un cadeau pour ma femme.', 'zoek'),
      S('Wat zoekt ge precies?', 'Que cherchez-vous exactement ?', 'zoekt')],
    'vinden': [S('Ik vind de kassa niet.', 'Je ne trouve pas la caisse.', 'vind'),
      S('Hebt ge gevonden wat ge zocht?', 'Vous avez trouvé ce que vous cherchiez ?', 'gevonden')],
    'open': [S('De winkel is nog open.', 'Le magasin est encore ouvert.', 'open'),
      S('Op zondag zijn wij open tot twaalf uur.', 'Le dimanche nous sommes ouverts jusqu’à midi.', 'open')],
    'gesloten': [S('De bakker is maandag gesloten.', 'Le boulanger est fermé le lundi.', 'gesloten'),
      S('Het gemeentehuis is nu gesloten.', 'La maison communale est fermée maintenant.', 'gesloten')],

    /* ---- unité 11 : le corps et le médecin ---- */
    'ziek': [S('Mijn zoon is ziek vandaag.', 'Mon fils est malade aujourd’hui.', 'ziek'),
      S('Ik ben ziek en blijf thuis.', 'Je suis malade et je reste à la maison.', 'ziek')],
    'de pijn': [S('Ik heb pijn aan mijn rug.', 'J’ai mal au dos.', 'pijn'),
      S('De pijn is sinds gisteren erger.', 'La douleur est pire depuis hier.', 'pijn')],
    'het hoofd': [S('Ik heb pijn aan mijn hoofd.', 'J’ai mal à la tête.', 'hoofd'),
      S('Mijn hoofd doet zeer.', 'J’ai mal à la tête.', 'hoofd')],
    'de keel': [S('Mijn keel doet zeer sinds maandag.', 'J’ai mal à la gorge depuis lundi.', 'keel'),
      S('Een pijnlijke keel en wat koorts.', 'Une gorge douloureuse et un peu de fièvre.', 'keel')],
    'de buik': [S('Het kind heeft buikpijn.', 'L’enfant a mal au ventre.', 'buikpijn'),
      S('Mijn buik doet zeer na het eten.', 'J’ai mal au ventre après avoir mangé.', 'buik')],
    'de rug': [S('Ik heb last van mijn rug.', 'J’ai des problèmes de dos.', 'rug'),
      S('Mijn rug doet zeer van het werken.', 'J’ai mal au dos à force de travailler.', 'rug')],
    'de koorts': [S('Ik heb koorts sinds gisteren.', 'J’ai de la fièvre depuis hier.', 'koorts'),
      S('Het kind heeft achtendertig graden koorts.', 'L’enfant a trente-huit de fièvre.', 'koorts')],
    'de hoest': [S('Ik heb een droge hoest.', 'J’ai une toux sèche.', 'hoest'),
      S('De hoest blijft al een week.', 'La toux dure depuis une semaine.', 'hoest')],
    'de dokter': [S('Ik ga morgen naar de dokter.', 'Je vais chez le médecin demain.', 'dokter'),
      S('De dokter geeft mij een voorschrift.', 'Le médecin me donne une ordonnance.', 'dokter')],
    'de apotheek': [S('De apotheek is naast de bakker.', 'La pharmacie est à côté du boulanger.', 'apotheek'),
      S('Ik haal het medicijn in de apotheek.', 'Je prends le médicament à la pharmacie.', 'apotheek')],
    'het medicijn': [S('Dit medicijn neemt ge drie keer per dag.', 'Ce médicament se prend trois fois par jour.', 'medicijn'),
      S('Het medicijn helpt goed.', 'Le médicament aide bien.', 'medicijn')],
    'het voorschrift': [S('Zonder voorschrift krijgt ge dat niet.', 'Sans ordonnance vous ne l’obtenez pas.', 'voorschrift'),
      S('Ik heb het voorschrift bij.', 'J’ai l’ordonnance sur moi.', 'voorschrift')],
    'de wachtzaal': [S('Er zitten vijf mensen in de wachtzaal.', 'Il y a cinq personnes dans la salle d’attente.', 'wachtzaal'),
      S('Wacht u even in de wachtzaal.', 'Attendez un instant dans la salle d’attente.', 'wachtzaal')],
    'het ziekenhuis': [S('Het ziekenhuis ligt buiten de stad.', 'L’hôpital est en dehors de la ville.', 'ziekenhuis'),
      S('Zij werkt in het ziekenhuis.', 'Elle travaille à l’hôpital.', 'ziekenhuis')],
    'beter': [S('Ik voel mij al beter.', 'Je me sens déjà mieux.', 'beter'),
      S('Morgen gaat het beter.', 'Demain ça ira mieux.', 'beter')],
    'sinds': [S('Ik heb koorts sinds maandag.', 'J’ai de la fièvre depuis lundi.', 'sinds'),
      S('Sinds gisteren voel ik mij slecht.', 'Depuis hier je me sens mal.', 'Sinds')],
    'voelen': [S('Ik voel mij niet goed.', 'Je ne me sens pas bien.', 'voel'),
      S('Hoe voelt ge u vandaag?', 'Comment vous sentez-vous aujourd’hui ?', 'voelt')],
    'rusten': [S('De dokter zegt dat ik moet rusten.', 'Le médecin dit que je dois me reposer.', 'rusten'),
      S('Rust een paar dagen thuis.', 'Reposez-vous quelques jours à la maison.', 'Rust')],
    'langskomen': [S('Kunt ge morgen langskomen?', 'Pouvez-vous passer demain ?', 'langskomen'),
      S('Ik kom straks langs.', 'Je passe tout à l’heure.', 'kom')],

    /* ---- unité 12 : météo et week-end ---- */
    'het weer': [S('Het weer is slecht vandaag.', 'Le temps est mauvais aujourd’hui.', 'weer'),
      S('Met dit weer blijf ik thuis.', 'Avec ce temps je reste à la maison.', 'weer')],
    'de regen': [S('In de regen neem ik de bus.', 'Sous la pluie je prends le bus.', 'regen'),
      S('Na de regen komt de zon.', 'Après la pluie vient le soleil.', 'regen')],
    'de zon': [S('De zon schijnt eindelijk.', 'Le soleil brille enfin.', 'zon'),
      S('Met de zon is het gezellig buiten.', 'Avec le soleil c’est agréable dehors.', 'zon')],
    'de wind': [S('Er staat veel wind vandaag.', 'Il y a beaucoup de vent aujourd’hui.', 'wind'),
      S('Met die wind fiets ik niet.', 'Avec ce vent je ne fais pas de vélo.', 'wind')],
    'koud': [S('Het is koud voor september.', 'Il fait froid pour un mois de septembre.', 'koud'),
      S('Ik heb het koud.', 'J’ai froid.', 'koud')],
    'warm': [S('Het is warm in het kantoor.', 'Il fait chaud au bureau.', 'warm'),
      S('Een warme dag voor de tijd van het jaar.', 'Une journée chaude pour la saison.', 'warme')],
    'het weekend': [S('Dit weekend blijven wij thuis.', 'Ce week-end nous restons à la maison.', 'weekend'),
      S('Een goed weekend, collega!', 'Bon week-end, collègue !', 'weekend')],
    'het verlof': [S('Volgende week neem ik verlof.', 'La semaine prochaine je prends congé.', 'verlof'),
      S('Mijn collega is met verlof.', 'Mon collègue est en congé.', 'verlof')],
    'het voetbal': [S('Op zondag kijk ik voetbal.', 'Le dimanche je regarde le football.', 'voetbal'),
      S('Mijn zoon speelt voetbal in {stad}.', 'Mon fils joue au football à {stad}.', 'voetbal')],
    'de match': [S('De match begint om acht uur.', 'Le match commence à vingt heures.', 'match'),
      S('Hebt ge de match gezien?', 'Tu as vu le match ?', 'match')],
    'plezant': [S('Dat was een plezante avond.', 'C’était une soirée chouette.', 'plezante'),
      S('Het werk is plezant met die collega’s.', 'Le travail est chouette avec ces collègues.', 'plezant')],
    'gezellig': [S('Het was gezellig bij de buren.', 'C’était convivial chez les voisins.', 'gezellig'),
      S('Een gezellig café in het dorp.', 'Un café convivial dans le village.', 'gezellig')],
    'ambetant': [S('Die vertraging is ambetant.', 'Ce retard est embêtant.', 'ambetant'),
      S('Sorry, dat is ambetant voor u.', 'Désolé, c’est embêtant pour vous.', 'ambetant')],
    'goesting': [S('Ik heb goesting in een pintje.', 'J’ai envie d’une bière.', 'goesting'),
      S('Vandaag heb ik geen goesting om te koken.', 'Aujourd’hui je n’ai pas envie de cuisiner.', 'goesting')],
    'kijken': [S('Wij kijken vanavond naar de match.', 'Nous regardons le match ce soir.', 'kijken'),
      S('Ik kijk niet veel televisie.', 'Je ne regarde pas beaucoup la télévision.', 'kijk')],
    'gedaan': [S('Het werk is gedaan.', 'Le travail est fini.', 'gedaan'),
      S('Om vijf uur is het gedaan.', 'À dix-sept heures c’est fini.', 'gedaan')],
    'niks': [S('Dit weekend doen wij niks.', 'Ce week-end on ne fait rien.', 'niks'),
      S('Er is niks aan de hand.', 'Il n’y a rien de grave.', 'niks')],
    'lang': [S('Het was een lange dag.', 'Ça a été une longue journée.', 'lange'),
      S('Hoe lang duurt de rit?', 'Combien de temps dure le trajet ?', 'lang')],
    'volgende': [S('Volgende week ben ik met verlof.', 'La semaine prochaine je suis en congé.', 'Volgende'),
      S('Tot volgende maandag!', 'À lundi prochain !', 'volgende')]
  };

  /* Les phrases s'accrochent aux mots par leur forme exacte, article compris :
     si un mot est renommé dans le lexique, sa phrase ne suit pas en silence. */
  let missing = [];
  NL.content.units.forEach(u => (u.words || []).forEach(w => {
    if (EX[w.nl]) w.drills = EX[w.nl];
  }));
  Object.keys(EX).forEach(nl => {
    if (!NL.content.units.some(u => (u.words || []).some(w => w.nl === nl))) missing.push(nl);
  });
  NL.content.exampleReport = { attached: Object.keys(EX).length - missing.length, missing };
})();
