/* Toute l'interface, en un seul endroit. Une seule langue d'interface, donc une
   table plate plutôt qu'un système i18n complet — ça garde le ton cohérent et
   rend un basculement vers le néerlandais possible plus tard. */
NL.t = {
  /* --- navigation : le libellé français, avec le mot néerlandais dessous --- */
  nav: [
    { id: 'vandaag', fr: 'Aujourd’hui', nl: 'vandaag' },
    { id: 'leerpad', fr: 'Parcours', nl: 'leerpad' },
    { id: 'praten', fr: 'Parler', nl: 'praten' },
    { id: 'luisteren', fr: 'Écouter', nl: 'luisteren' },
    { id: 'meer', fr: 'Plus', nl: 'meer' }
  ],

  brandSub: '{stad} · {bedrijf}',

  /* --- boutons et mots partout --- */
  check: 'Vérifier', next: 'Continuer', skip: 'Passer', close: 'Fermer',
  back: 'Retour', start: 'Commencer', again: 'Recommencer', cancel: 'Annuler',
  save: 'Enregistrer', del: 'Supprimer', open: 'Ouvrir', listen: 'Écouter',
  slow: 'Lentement', replay: 'Encore', stop: 'Stop', speak: 'Parler',
  dunno: 'Aucune idée', yes: 'Oui', no: 'Non',

  /* --- écran Aujourd’hui --- */
  todayEyebrow: 'Aujourd’hui',
  todayAllDone: 'Tout est à jour.',
  todayAllDoneSub: 'Rien à revoir. Réviser trop tôt ne sert à rien — ça brûle la répétition. Repasse plus tard, ou travaille quelque chose de précis ci-dessous.',
  todayReady: n => n + (n === 1 ? ' élément t’attend' : ' éléments t’attendent'),
  todaySplit: (due, fresh, mins) => due + ' à revoir, ' + fresh + ' nouveaux · environ ' + mins + ' minutes.',
  todayStart: 'Démarrer la session',
  todayPractise: 'Travailler une conversation',
  todayGoal: (a, b) => a + ' / ' + b + ' nouveaux',
  statStreak: n => n === 1 ? 'jour d’affilée' : 'jours d’affilée',
  statSaid: 'dits à voix haute',
  statCourse: 'du cours',
  morepractice: 'Continuer autrement',

  /* --- accueil, premier lancement --- */
  firstTitle: 'Ce que tu entends déjà compte.',
  firstBody: 'Tu entends du néerlandais depuis des années. Commencer à « de man eet brood » gaspillerait des semaines. Un test de cinq minutes te place là où tu es vraiment.',
  firstDoTest: 'Faire le test de niveau',
  firstSkip: 'Commencer de zéro',

  /* --- parcours --- */
  pathEyebrow: 'Parcours',
  pathTitle: 'A1 → B2, en douze unités',
  pathBody: 'Les unités alimentent le planificateur en nouvelles matières. Tu ne dois pas finir une unité pour ouvrir la suivante : elle s’ouvre d’elle-même quand l’essentiel de la précédente a été vu.',
  pathSolid: (a, b) => a + ' éléments sur ' + b + ' sont bien ancrés.',
  unitSeen: (a, b) => a + '/' + b + ' vus',
  unitStart: 'Commencer cette unité',
  unitPractise: 'Travailler cette unité',
  unitLocked: n => 'S’ouvre quand l’unité ' + n + ' aura été vue en grande partie.',
  trackWork: 'travail', trackLife: 'quotidien', trackBoth: 'les deux',

  /* --- session --- */
  sessionOf: (a, b) => a + '/' + b,
  again2: 'encore une fois',
  praise: ['Bien joué !', 'Exact.', 'Parfait.', 'C’est ça.', 'Amai, bien !'],
  wrongTitle: 'La bonne réponse',
  hereThey: 'Ici on dit :',
  matchHint: 'Touche un mot néerlandais, puis sa traduction.',
  doneFlawless: 'Sans faute.',
  doneOk: 'Session terminée.',
  doneSpoken: n => 'Tu as dit ' + n + (n === 1 ? ' élément' : ' éléments') + ' à voix haute. Ce sont ceux qui sortiront de ta bouche dans un magasin.',
  doneNoSpoken: 'Rien de dit à voix haute cette fois — les exercices de prononciation arrivent quand les éléments montent dans l’échelle.',
  tallyXp: 'XP', tallyRight: 'Juste', tallyDays: 'Jours', tallyTime: 'Durée',
  sessionMore: 'Encore une session',
  sessionBack: 'Retour à Aujourd’hui',
  nothingDue: 'Rien à faire — pour l’instant.',
  nothingDueBody: 'Tout ce que tu as rencontré est programmé pour plus tard. C’est le planificateur qui fait son travail, pas un bug : réviser trop tôt gâche la répétition.',
  nothingDueGo: 'Commencer une nouvelle unité',

  /* --- exercices --- */
  exPick: 'C’est lequel ?',
  exRecall: 'Ça veut dire quoi ?',
  exArticle: 'De ou het ?',
  exBank: 'Dis-le en néerlandais',
  exOrder: 'Remets la phrase dans l’ordre',
  exCloze: 'Complète le mot manquant',
  exDictation: 'Tape ce que tu entends',
  exType: 'Écris-le en néerlandais',
  exSpeak: 'Dis-le à voix haute',
  exMatch: 'Associe les paires',
  exIntrus: 'Lequel n’a pas le même article ?',
  exCorrige: 'Une faute s’est glissée. Où ?',
  exVlaams: 'Comment le dit-on ici ?',
  exOpen: 'À toi d’écrire',
  openPlaceholder: 'Écris ta réponse en néerlandais…',
  openModel: 'Un exemple :',
  rungs: ['découverte', 'reconnaissance', 'à l’oreille', 'à l’écrit', 'à voix haute', 'maîtrisé', 'ancré'],
  tapWords: 'Touche les mots ci-dessous',
  specialLetters: 'Lettres spéciales',
  typeHere: 'Tape en néerlandais',
  heardWhat: 'Qu’as-tu entendu ?',

  /* --- micro --- */
  micTap: 'Touche et dis la phrase.',
  micListening: 'J’écoute…',
  micHeard: 'Entendu :',
  micRetry: n => 'Réessayer (' + n + ')',
  micAnyway: 'Continuer quand même',
  micSaidIt: 'Je l’ai dit',
  micNotYet: 'Pas encore',
  micNotedOk: 'Noté comme réussi.',
  micNotedNo: 'Noté — on le retravaillera.',
  micDenied: 'Micro bloqué. Autorise-le dans la barre d’adresse, ou évalue-toi toi-même.',
  micSilence: 'Rien entendu. Touche à nouveau et parle un peu plus fort.',
  micNetwork: 'La reconnaissance a besoin d’une connexion. Dis-le à voix haute et évalue-toi.',
  micFail: 'Ça n’a pas marché. Réessaie.',
  micNoBrowser: 'Ce navigateur ne reconnaît pas la parole — Opera n’a pas ce service. Enregistre-toi et compare, ou évalue-toi.',
  micOffline: 'Hors ligne : la reconnaissance ne peut pas te noter. Dis-le quand même à voix haute et évalue-toi honnêtement.',
  recRecord: 'M’enregistrer',
  recStop: 'Arrêter',
  recModel: 'Le modèle',
  recYours: 'Ta version',
  recBoth: 'Écouter les deux',
  recAgain: 'Réenregistrer',
  recHint: 'Écoute le modèle, enregistre-toi, compare. C’est ainsi qu’on travaillait en laboratoire de langues pendant cinquante ans.',

  /* --- parler / scénarios --- */
  talkEyebrow: 'Conversations',
  talkTitle: 'Réponds',
  talkBody: 'Chaque scénario rejoue un échange réel. Tu choisis ce que tu dis, puis tu le <b>dis à voix haute</b> — parce que choisir les bons mots et les produire sont deux compétences différentes, et une seule aide au comptoir d’une boulangerie.',
  talkLife: 'Au village', talkLifeSub: 'Les conversations qui arrivent, que tu sois prêt ou non.',
  talkWork: 'Au travail', talkWorkSub: 'Le néerlandais du travail, là où la pression est la plus forte et les formules les plus fixes.',
  talkDone: 'Refaire',
  scnOver: 'Conversation terminée.',
  scnSpoken: 'Dits',
  scnAgain: 'Refaire',
  scnBack: 'Retour aux conversations',
  scnStd: 'standard :',

  /* --- écouter --- */
  listenEyebrow: 'Écouter',
  listenTitle: 'Du flamand à vitesse réelle',
  listenBody: 'Chaque phrase vient d’un scénario, jouée à plein régime avec la prononciation flamande et sans texte à l’écran. Comprendre à vitesse normale est ce qui décide si une conversation survit au-delà de la deuxième phrase.',
  listenUnderstand: 'Comprendre',
  listenUnderstandSub: 'Huit phrases, aucun texte. Qu’est-ce qui a été dit ?',
  listenRepeat: 'Répéter après',
  listenRepeatSub: 'Shadowing : entends la phrase, redis-la, reçois un score.',
  listenWhatSaid: 'Qu’a dit cette personne ?',
  listenRepeatTitle: 'Répète, aussi vite que tu l’entends',
  listenNoText: 'Pas de texte. Écoute autant de fois que tu veux.',
  listenFrom: 'extrait de',
  listenDone: 'Terminé.',
  listenGoodEar: 'Ton oreille est en avance sur ta bouche — c’est normal, et c’est utile.',
  listenHardEar: 'Difficile. La parole rapide arrive en dernier ; refais cette série quelques fois et ça bouge.',
  listenShadowDone: 'Le shadowing travaille en silence. Dix minutes valent mieux qu’une heure de lecture.',
  listenUnderstood: 'Compris',
  listenMore: 'Encore une série',

  /* --- mots --- */
  wordsEyebrow: 'Mes mots',
  wordsTitle: n => n + ' mots en route',
  wordsBody: 'Tout ce que tu as rencontré, avec l’étape atteinte. Ajoute les tiens — le titre d’un collègue, ta rue, le mot qui t’a pris de court à midi — et le planificateur les travaillera comme les autres.',
  wordsAdd: 'Ajouter un mot à moi',
  wordsNothing: 'Rien encore. Fais une session et ça apparaît ici.',
  wordsNoResult: 'Rien trouvé.',
  wordsSearch: 'Rechercher…',
  wordsAll: 'tous', wordsWeak: 'fragiles', wordsStrong: 'solides', wordsMine: 'à moi',
  wordsNl: 'Néerlandais', wordsFr: 'Français', wordsBe: 'Comme on dit ici',
  wordsOptional: '(facultatif)',
  wordsNeedBoth: 'Le néerlandais et le français sont nécessaires.',
  wordsAdded: 'Ajouté — il reviendra tout seul.',
  wordsHere: 'ici :',

  /* --- fiches --- */
  sheetsEyebrow: 'Antisèches',
  sheetsTitle: 'Pour le couloir',
  sheetsBody: 'Huit fiches à ouvrir trente secondes avant d’en avoir besoin. Touche une ligne pour l’entendre.',
  sheetsAll: 'Toutes les antisèches',

  /* --- registre et sons --- */
  regEyebrow: 'Standard et flamand',
  regTitle: 'Dis à gauche. Comprends à droite.',
  regBody: 'Produis la colonne de gauche et tu es correct partout, y compris à l’écrit au travail. Reconnais celle de droite ou tu perds la moitié de ce qu’on te dit autour de toi. C’est la séparation qu’aucun cours de néerlandais des Pays-Bas ne te montre.',
  regStd: 'Néerlandais standard', regBe: 'Ce que tu entends ici',
  loansTitle: 'Le français caché dans le flamand',
  loansBody: 'Un francophone a une longueur d’avance qu’un anglophone n’a pas : une part du flamand vient directement du français. Voici ce que tu sais déjà sans le savoir.',
  fauxTitle: 'Les faux amis',
  fauxBody: 'Le revers de la médaille. Ceux-là coûtent plus cher que les emprunts ne rapportent.',
  soundsEyebrow: 'Les sons',
  soundsTitle: 'Le g doux, et le reste',
  soundsBody: 'La Flandre prononce plusieurs de ces sons autrement que le nord. Bonne nouvelle : trois voyelles néerlandaises existent déjà en français, ce qu’un anglophone n’a pas.',
  soundsEasy: 'tu l’as déjà',
  soundsWatch: 'attention',
  dehetTitle: 'Les familles de het',
  dehetBody: 'Environ 70% des mots het suivent une règle. Apprends les familles au lieu des 425 articles un par un — et ne traduis jamais depuis le français : het huis est neutre, la maison est féminine.',
  dehetHet: 'Prennent het', dehetDe: 'Prennent de',
  dehetSure: 'sans exception',

  /* --- test de niveau --- */
  placeEyebrow: 'Test de niveau · aucune pénalité',
  placeQ: 'Qu’est-ce que ça veut dire ?',
  placeHigh: 'Tu comprends déjà bien plus que tu ne crois.',
  placeMid: 'Il y a déjà une base, surtout passive.',
  placeLow: 'On commence au début — et c’est très bien.',
  placeSeeded: n => 'Reconnaître un mot n’est pas savoir le dire, donc rien n’a été marqué comme acquis : ' + n + ' éléments ont simplement été placés plus haut dans l’échelle, en sautant les présentations dont tu n’as clairement pas besoin. Ils doivent encore atteindre l’étape orale.',
  placeNone: 'Rien n’a été avancé, donc tu pars propre. C’est le point de départ honnête.',
  placeRecognised: 'Reconnus', placeAdvanced: 'Avancés',
  placeUnits: 'Unités', placeAsked: 'Questions',
  placeRule: (a, b) => a + ' bonnes réponses sur ' + b + ' pour créditer l’unité et passer à la suivante.',
  placeStops: n => 'Le test s’arrête à « ' + n + ' » : c’est de là que tu pars.',
  placeFirst: 'Commence ta première session',
  placeLater: 'Plus tard',

  /* --- réglages --- */
  setTitle: 'Réglages',
  setTheme: 'Thème', setSystem: 'Système', setLight: 'Clair', setDark: 'Sombre',
  setPractice: 'Exercice',
  setFlemish: 'Montrer la variante flamande',
  setAutoplay: 'Lire l’audio automatiquement',
  setSfx: 'Petits sons',
  setGoal: 'Nouveaux éléments par jour',
  setMine: 'Rends-le tien',
  setMineNote: 'Ces trois mots remplacent les espaces réservés dans tout le cours : tu t’entraînes sur tes vraies phrases, pas celles de quelqu’un d’autre. Ils restent sur cet appareil.',
  setName: 'Ton prénom',
  setTown: 'Ta commune',
  setCompany: 'Ton employeur',
  setPace: 'Rythme',
  paceCalme: 'Tranquille', paceNormal: 'Normal', paceIntensif: 'Intensif',
  paceNote: p => p.mins + ' min par jour · ' + p.cap + ' exercices maximum',
  paceWhy: 'Le plafond quotidien est ce qui empêche les révisions de s’accumuler jusqu’à deux heures par jour au sixième mois. Ce qui déborde attend son tour.',
  budgetDone: 'Le quota du jour est atteint. C’est voulu : demain sera plus léger.',
  migrated: 'Progression remise à zéro — l’ancien test de niveau créditait des unités entières sans preuve.',
  unitGate: (a, b) => 'L’unité suivante s’ouvre à ' + b + '% travaillés — tu es à ' + a + '%.',
  unitLevel: n => 'Niveau ' + n + ' / 5',
  masteredOf: (a, b) => a + ' maîtrisés sur ' + b,
  metOf: (a, b) => a + ' rencontrés sur ' + b,
  currentUnit: 'À faire maintenant',
  setVoice: 'Voix et micro',
  setDoctor: 'Tester le son et le micro',
  setStorage: 'Stockage :',
  setExport: 'Exporter ma progression',
  setImport: 'Importer une sauvegarde',
  setReset: 'Tout effacer',
  setResetTitle: 'Effacer toute la progression ?',
  setResetBody: 'Chaque révision, chaque série, chaque mot ajouté. C’est définitif.',
  setResetYes: 'Oui, tout effacer',
  quitTitle: 'Arrêter la session ?',
  quitBody: 'Ce que tu as déjà réussi est gardé. Le reste revient simplement plus tard.',
  quitYes: 'Arrêter',
  quitNo: 'Continuer',
  exported: 'Sauvegarde téléchargée.',
  imported: 'Progression restaurée.',
  importFailed: 'Ce fichier n’est pas une sauvegarde valable.',
  wiped: 'Tout est effacé.',

  /* --- statistiques --- */
  weekTitle: 'Cette semaine',
  statLearning: 'en cours', statStrong: 'solides', statSpoken: 'dits à voix haute',
  statBest: 'plus longue série',
  days: ['dim', 'lun', 'mar', 'mer', 'jeu', 'ven', 'sam'],

  /* --- audio doctor --- */
  docEyebrow: 'Son et micro',
  docTitle: 'Qu’est-ce qui marche chez toi ?',
  docRun: 'Lancer le test',
  docRecheck: 'Revérifier',
  docBrowser: 'Navigateur',
  docFrame: 'Page intégrée',
  docVoices: 'Voix trouvées',
  docNoVoice: 'Aucune voix néerlandaise installée.',
  docHeard: 'Tu as entendu quelque chose ?',
  docPlayTest: 'Jouer la phrase test',
  docMicTest: 'Tester le micro',
  docTierTitle: 'Ton niveau actuel',
  docFixTitle: 'Installer la voix flamande sur Windows',
  docFixSteps: [
    'Paramètres → Heure et langue → Langue et région',
    'Ajouter une langue → Nederlands (België)',
    'Coche « Voix » (Speech) dans les fonctionnalités facultatives',
    'Installe, puis reviens ici et clique sur Revérifier'
  ],
  docFixNote: 'Ça installe une voix système que tous les navigateurs voient, Opera compris. Pas besoin de redémarrer.'
};
